### ISSUE TITLE
How to use translation pre-trained model without bpecodes?

### ISSUE THREAD

**Issue by pamin2222** [pytorch/fairseq#1052]
I am trying to use pre-trained models provided by FAIRSEQ to evaluate translation score and use as an initial weight. I am not sure how to use it correctly.

I followed the [Evaluating Pre-trained Models guide](https://fairseq.readthedocs.io/en/latest/getting_started.html) and I can run wmt14.en-fr.fconv-py without a problem. 

However, the [LightConv Chinese-English](https://github.com/pytorch/fairseq/blob/master/examples/pay_less_attention_paper/README.md) provides only dict.en.txt, dict.zh.txt, and model.pt.

- How should I pre-process the data to feed it into the model?

- Is there a 'bpecodes' provided for preprocessing step? 

- Are there an example commands of fine-tuning a new model by using the pre-trained model weight?

Thank you!

**Comment by myleott** [comment]
We need to add the scripts to preprocess Zh-En. Will close this in favor of #1260

**Comment by GeorgeS2019** [comment]
@myleott  We are provided with pre-trained model with working test data to validate the provided pre-trained model. 

However, we are NOT ABLE to make use of the provided [pre-trained model](https://dl.fbaipublicfiles.com/fairseq/models/dynamicconv/wmt17.zh-en.lightconv-glu.tar.bz2) (**BECAUSE IT COMEs**) **without** the BPE (bpecodes)

I doubt by having the scripts to preprocess Zh-En will address the fact that we are NOT ABLE TO use the provided[ pre-trained model](https://dl.fbaipublicfiles.com/fairseq/models/dynamicconv/wmt17.zh-en.lightconv-glu.tar.bz2)

**Comment by myleott** [comment]
The BPE codes are now available in a new set of archives with a .tar.gz extension. I've also updated the README with a bunch of additional usage instructions via torch.hub: https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper#example-usage-torchhub
