### ISSUE TITLE
Model size with averaging checkpoints and fp16

### ISSUE THREAD

**Issue by sidjain007** [pytorch/fairseq#1079]
Does average_checkpoints support fp16?

I have a model trained with standard fp precision. The size of each model checkpoint including the averaged checkpoint is 454 MiB. When I train with fp16, I am able to reduce the size for each model checkpoint to 378 MiB. However, the averaged checkpoint model increases back to the original 454 MiB. 

In both tests, I average the last 10 checkpoints generated,

**Comment by patrik-lambert** [comment]
I think it is because the averaging is performed on CPU, which is not compatible with fp16 and requires a conversion to float:
`lambda s, _: torch.serialization.default_restore_location(s, 'cpu')`
...
`            if isinstance(p, torch.HalfTensor):
                p = p.float()
`
I solved the issue performing the averaging on GPU, replacing 'cpu' by 'cuda':
`lambda s, _: torch.serialization.default_restore_location(s, 'cuda')`

**Comment by lematt1991** [comment]
Yes @patrik-lambert is correct in his explanation.
