### ISSUE TITLE
Multilingual translation  

### ISSUE THREAD

**Issue by amrit-bhaskar** [pytorch/fairseq#1123]
I am training multilingual translation for three languages.
The languages are English,Hindi and Bengali.
I am training a single model for translating English-Hindi,English-Bengali,Hindi-English,Begali-English as described here: https://github.com/pytorch/fairseq/tree/master/examples#multilingual-translation.

After training for 30 epochs,
While Testing for English to Hindi,
    The output translation contains Hindi and Bengali both instead of only Hindi.

Other Directions from Hindi to English and Bengali to English is coming correctly(Towards English).

My training details are as below:
     Hindi -English corpus : 1689738 sentences
     Bengali-English corpus : 387425 sentences

**Comment by myleott** [comment]
@pipibjc

**Comment by pipibjc** [comment]
@amrit-bhaskar, could you provide your training log and fairseq version you used? I can help to take a look.

**Comment by pipibjc** [comment]
I forget to mention, you don't need to provide the whole training log. Just the first part that includes `Namespace(...` so that I can check the parameters. 

I had a fix [1566cfb](https://github.com/pytorch/fairseq/commit/1566cfb9634fd06c551df510ac24f36c4bfca5a6#diff-39d53d971eac6be897d08935b6a6a5f7) that fixed a bug for one-to-many multilingual translation. If your fairseq checkout is older than that, you could patch the fix, re-train and evaluate your result to see if that fix your problem. Feel free to still share your training log so that I can help to double check.
