### ISSUE TITLE
wave2vec: Why always select the audio with minimum length to decide the batch dimension?

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#1129]
Why don't we add padding? Is there any reason only to remove excess by selecting minimal length as in this [line?](https://github.com/pytorch/fairseq/blob/master/fairseq/data/audio/raw_audio_dataset.py#L89)

**Comment by huihuifan** [comment]
@okhonko

**Comment by alexeib** [comment]
padding would add more overhead because then you have to take it into account across the entire model, e.g. when selecting negatives, when computing loss, etc. We sort examples by length before batching them anyway, so examples of similar length are already grouped together and we found that cropping 10s from each audio file works best anyways. But you are welcome to try and let us know results!
