### ISSUE TITLE
How to reproduce "Back-translation at scale" paper, WMT'14 En-De

### ISSUE THREAD

**Issue by nxphi47** [pytorch/fairseq#1330]
Hi the authors,

Thank you for the paper and this framework.

From the instruction here: https://github.com/pytorch/fairseq/tree/master/examples/backtranslation

I don't see how to reproduce the results, including how to download the used monolingual data?

Can you guide me step-by-step on how to reproduce it?

Thank you.

**Comment by edunov** [comment]
Hi, thanks for the interest, 

For En-De, all the data for this paper can be downloaded here: http://www.statmt.org/wmt18/translation-task.html  we used News Crawl as a sort of monolingual data. 

We don't provide exact step by step instructions because it is system dependent, and difficult to maintain up to date as fairseq evolves. The basic steps however are: 

1) Train bitext system in reverse direction
2) Back-translate the monolingual data using the system trained in 1
3) Combine bitext and monolingual data and train a system in forward direction

If you have specific questions about any of the steps, please post here and one of us should be able to provide answers
