### ISSUE TITLE
Refactor training code and metrics to use ignite

### ISSUE THREAD

**Issue by erip** [pytorch/fairseq#1648]
## 🚀 Feature Request

Custom training, logging, and checkpointing code should be replaced with ignite.

### Motivation

Because ignite is the official Pytorch training library and has support for metrics, it seems like  some of fairseq's code reinvents the wheel. It would be nice if ignite could fill the gaps instead.

### Pitch

Maintaining messy training, checkpointing, and metrics logic can introduce bugs -- ignite can do this for you.

### Alternatives

Keep the code as-is.

**Comment by myleott** [comment]
This would be interesting to explore. Do you have much experience with ignite and/or would you want to take a stab at it?

Two potential concerns:
1) events and hooks often become unwieldy and make the code less readable, especially as complexity grows. How do we manage this in a sensible way?
2) will we be able to port the various speed optimizations in our current Trainer into ignite? For example, apex FP16 is actually slower than fairseq's implementation due to not collapsing the parameters into a single buffer. Fairseq also has an alternative DDP implementation ("no_c10d" or LegacyDistributedDataParallel), which is necessary for a lot of cases where the pytorch DDP doesn't work properly; can we port that over as well?

Another alternative is pytorch-lightning, which already mirrors FairseqTask in many ways. Concern 2 above still applies.

What do you think?

**Comment by erip** [comment]
The readability question is tough to answer because it depends on how the logic is encapsulated, etc. I suspect that as the notional refactor begins, we can keep an eye on how it looks as a smoketest. 

I almost wonder if the two unique capabilities afforded by fairseq that you mentioned could be abstracted into their open libraries? I don't think ignite forces you into any particular AMP or DDP.

**Comment by erip** [comment]
I guess I didn't quite address this explicitly, but I think the `Trainer` would encapsulate this change in its entirety.
