### ISSUE TITLE
fairseq-train: error: unrecognized arguments: --eval-bleu --eval-bleu-args {"beam": 5, "max_len_a": 1.2, "max_len_b": 10} --eval-bleu-detok moses --eval-bleu-remove-bpe --eval-bleu-print-samples

### ISSUE THREAD

**Issue by hljjjmssyh** [pytorch/fairseq#1695]
When I started to train a new model for the translation task, I met some errors.

**Comment by myleott** [comment]
Ah, the `--eval-bleu` functionality is only available in master right now. You can safely remove those arguments, or you can install fairseq by cloning and installing from source.

**Comment by lematt1991** [comment]
Sounds like this has been resolved.  If you are still having problems, please open another issue.

**Comment by heiwais25** [comment]
Could I know why `--eval-bleu` option is not included in the `fairseq-train` of the latest version?

**Comment by Anwarvic** [comment]
@heiwais25 because it's only related to translation tasks, you can find the full documentation for translation-related tags in the [following page](https://fairseq.readthedocs.io/en/v0.10.2/tasks.html#translation). To enable these arguments, your `task` argument needs to be set to `--task=translation`.
