### ISSUE TITLE
What is the advantage of buffers?

### ISSUE THREAD

**Issue by sshleifer** [pytorch/fairseq#1849]
In sequence_generator.py https://github.com/pytorch/fairseq/blob/17e90c3c6f8665e21a54b2ef4a2e4f37ad809b10/fairseq/sequence_generator.py#L164

and also in FairseqIncrementalDecoder
there is often the pattern of getting a tensor by name from a dictionary if it doesn't exist, otherwise allocating it.

I can think of many reasons why this might be better, but for the sake of learning wanted to hear why this repo uses that pattern.

Thanks in advance!

**Comment by myleott** [comment]
Good question! A long time ago we found it slightly reduced peak memory usage, since it will sometime reuse the memory of the buffers instead of allocating new memory.

That said, we'll soon be removing this manual buffer management from sequence generator. It complicates the code a bit, and doesn't play nicely with torch.jit scripting.
