### ISSUE TITLE
BART as a Language Model

### ISSUE THREAD

**Issue by tuhinjubcse** [pytorch/fairseq#1883]
#### What is your question?
I am interested to use BART as a Language Model to assign the Language modeling score (Perplexity score) of a sentence. 
Something on the lines of https://github.com/huggingface/transformers/issues/473

Environment
- fairseq Version (e.g., 1.0 or master): 0.9.0
- PyTorch Version (e.g., 1.0) 1.3.1
- OS (e.g., Linux): Linux
- How you installed fairseq (pip, source):
- Build command you used (if compiling from source):
- Python version: 3.7.3
- CUDA/cuDNN version: 10.1.243
- GPU models and configuration: RTX 2080 ( 4 gpus)

**Comment by tuhinjubcse** [comment]
@myleott  any pointers ?

**Comment by didge-rydu** [comment]
I'm not an author of this repository but I can tell you that BART is not a language model, so the definition of LM perplexity does not really apply here. You would have to get creative.
People have tried to do this with BERT (which is also not a language model) so that might be a good starting point for you to search.

**Comment by ruoguodayu** [comment]
@tuhinjubcse Hello,
How to use BART as Language Model ? Could you tell me the method? Or is there any relative code?
