### ISSUE TITLE
Issue loading BART-large model finetuned on CNN-DM dataset

### ISSUE THREAD

**Issue by rmovva** [pytorch/fairseq#2068]
I'm trying to load bart.large.cnn finetuned weights according to the README:

`bart = torch.hub.load('pytorch/fairseq', 'bart.large.cnn')`

But I'm getting the following error that indicates an off-by-one shape mismatch between the trained weights and the weights that the model architecture is expecting:

`RuntimeError: Error(s) in loading state_dict for BARTModel:
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([50265, 1024]) from checkpoint, the shape in current model is torch.Size([50264, 1024]).`

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version 1.5
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Python version: 3.7.6
 - CUDA/cuDNN version: 10.2

**Comment by zhaoruibing** [comment]
Same error here. Hopefully what I see can help to narrow down the issue a bit.

I have two machines, one works, one doesn't.
- Machine 1: Works. I initially setup BART (i.e. download model/cache) on this in Feb/Mar 2020.
- Machine 2: Throws error. I setup BART on this in the past week. However, it works if I overwrite fairseq cache with Machine 1's cache.

[Cause?] Since machine 2 works when I overwrite the fairseq cache with machine 1's copy (dated Mar 10). **Likely, something changed between Mar 10 to today caused this.** [fairseq_cache_1.zip](https://github.com/pytorch/fairseq/files/4540794/fairseq_cache_1.zip)
 is a copy of the working cached fairseq from machine 1, unsure which commit it is.

[Env] Machine 1 (no error):
- fairseq Version (e.g., 1.0 or master): master
- PyTorch Version 1.5.0
- OS (e.g., Linux): Linux
- How you installed fairseq (pip, source): Not installed. There is cache showing version 0.9.0 in setup.py. Cached files dated Mar 10, 2020.
- Python version: 3.6.9
- CUDA/cuDNN version: 10.2

[Env] Machine 2 (same error as _rmovva_)
- fairseq Version (e.g., 1.0 or master): master
- PyTorch Version 1.4.0
- OS (e.g., Linux): Linux
- How you installed fairseq (pip, source): Not installed. Cached files dated Apr 25, 2020. setup.py version is 0.9.0
- Python version: 3.6.10
- CUDA/cuDNN version: 10.2

[Temporary Fix] If you cannot wait to use BART (like me), try overwrite _~/.cache/torch/hub/pytorch_fairseq_master_ with a copy of fairseq from Mar 10, 2020 (I didn't test this) or the content from zip file (this is an _unsafe_ practice, use at your own risk).

[Misc]
- Machine 1 received a conda environment update and GPU driver reinstall in the past week.
- I also diff the model.pt from fbaipublicfiles.com and machine 1's cache, they are identical.

**Comment by tuhinjubcse** [comment]
Same issue any clue when this can be resolved ?

**Comment by myleott** [comment]
Fixed by 7a6519f84fed06947bbf161c7b66c9099bc4ce53
