### ISSUE TITLE
ROBERTA error when predicting: KeyError: 'mnli'

### ISSUE THREAD

**Issue by MarvinMogab** [pytorch/fairseq#2084]
Hello,
New here.

I finetuned Roberta large model with MNLI ( I know I can download it but I want to do it for research ), following the Glue Tasks finetuning guidlines adapted with MNLI dataset (highlighted here :point_right: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.glue.md)

When I tried to test manually some results, I got the following error:
**prediction = roberta.predict('mnli', tokens)**
**ERROR:  KeyError: 'mnli'** 

I made sure to initialize correctly the roberta model (using the **pre-processed** MNLI dataset) as per the below:
**roberta = RobertaModel.from_pretrained('../FineTuned',checkpoint_file='checkpoint_best.pt',data_name_or_path='../MNLI-bin')**

FYI, I already used before the 'mnli' classification head (in the predict() method) on a **downloaded MNLI fine tuned model** without any problems, but with the one I manually fine-tuned (with MNLI preprocessed dataset) I am encountering the issue.

Can you please advise ?

Big thanks

**Comment by myleott** [comment]
You probably need to use “sentence_classification_head” instead of “mnli”. See the instructions here: https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.glue.md#inference-on-glue-task

In the future you can give a custom name to the head during finetuning using `--classification-head-name`
