### ISSUE TITLE
Loading only encoder part of a pretrained enc-dec transformer model in fairseq 

### ISSUE THREAD

**Issue by semerekiros** [pytorch/fairseq#2271]
## ❓ Questions and Help
I am new to fairseq and wanted to ask you how I can load an encoder part so that I can use it in another model. 

from fairseq.models.transformer import TransformerModel
en2de = TransformerModel.from_pretrained("checkpoint/wmt16.en-de.joined-dict.transformer",
                                         checkpoint_file='model.pt',
                                         data_name_or_path='checkpoint/wmt16.en-de.joined-dict.transformer',
                                         bpe='subword_nmt',
                                         bpe_codes='checkpoint/wmt16.en-de.joined-dict.transformer/bpecodes')

**Comment by mingruimingrui** [comment]
Hey @semerekiros perhaps you can load the entire model before extracting only the encoder?
I think it would more more difficult to just load the encoder since fairseq saves model states (namespaces play a key part and there will be complexity involved when renaming them to only the portions involving the encoder).

**Comment by lematt1991** [comment]
Yes, I would follow @mingruimingrui's advice.

**Comment by semerekiros** [comment]
Solved it. Thanks
