### ISSUE TITLE
wav2vec: recommended exampe audio duration

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/fairseq#2432]
As far as I understand, LibriSpeech has average 4 second duration.

In the paper https://arxiv.org/abs/2006.11477 (sec. 4.2) it is mentioned that "Batches are built by cropping 250k audio samples, or 15.6sec, from each example. "

In the README you [mention](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec#training-a-new-model-with-the-cli-tools): "we recommend splitting each file into separate file 10 to 30 seconds in length".

Did you merge LibriSpeech files somehow to get 10-30 seconds? What is recommended individual audio duration for training? cc @alexeib 

I'm planning to train a model on 4 GPUs.

Thanks!

**Comment by shamoons** [comment]
Did you ever figure this out?

**Comment by alexeib** [comment]
for librispeech we just use the audio files as is. we crop 250k frames (for small model) or 320k frames (for wav2vec 2.0 big model) from each example - if they are smaller then we crop to length of smallest example in the batch

for librivox we use a version that was segmented into up to 36s since those files contain entire book recordings in each
