### ISSUE TITLE
module 'torch.nn' has no attribute 'GELU'

### ISSUE THREAD

**Issue by MrityunjoyS** [pytorch/fairseq#2510]
```
PYTHONPATH=/path/fairseq/ python3 examples/speech_recognition/infer.py /path/audio_file/wav2vec/ --task audio_pretraining \
--nbest 1 --path /path/audio_file/wav2vec_small.pt --gen-subset valid --results-path /path/audio_file/wav2vec/tmp/am/ --w2l-decoder kenlm \
--lm-model /path/kenlm/build/bin/ --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 \
--post-process letter
```

While running the above command, facing the bellow errors, please check -

_Traceback (most recent call last):
  File "examples/speech_recognition/infer.py", line 19, in <module>
    from fairseq import checkpoint_utils, options, progress_bar, utils, tasks
  File "/path/fairseq/fairseq/__init__.py", line 17, in <module>
    import fairseq.criterions  # noqa
  File "/path/fairseq/fairseq/criterions/__init__.py", line 10, in <module>
    from fairseq.criterions.fairseq_criterion import FairseqCriterion, LegacyFairseqCriterion
  File "/path/fairseq/fairseq/criterions/fairseq_criterion.py", line 11, in <module>
    from fairseq import metrics, utils
  File "/path/fairseq/fairseq/utils.py", line 23, in <module>
    from fairseq.modules import gelu, gelu_accurate
  File "/path/fairseq/fairseq/modules/__init__.py", line 19, in <module>
    from .gumbel_vector_quantizer import GumbelVectorQuantizer
  File "/path/fairseq/fairseq/modules/gumbel_vector_quantizer.py", line 12, in <module>
    class GumbelVectorQuantizer(nn.Module):
  File "/path/fairseq/fairseq/modules/gumbel_vector_quantizer.py", line 22, in GumbelVectorQuantizer
    activation=nn.GELU(),
AttributeError: module 'torch.nn' has no attribute 'GELU'_

**Comment by duterscmy** [comment]
Now my torch version is 1.5.1 and I have the same error. Could you give any suggestions?
`File "/ssd1/exec/caomingyu/works/rich_text/fairseq/fairseq/modules/gumbel_vector_quantizer.py", line 21, in GumbelVectorQuantizer
    activation=nn.GELU(),
AttributeError: module 'torch.nn' has no attribute 'GELU'`
@myleott

**Comment by duterscmy** [comment]
with my fairseq is the newest version ( git clone today)

**Comment by moon-home** [comment]
Hi, is there a solution now? I tried replace `nn.GELU` with `F.gelu`, but nothing changed at all. Why the message look like it's not recognizing the `functional as F`? I am using torch 1.6

```
/notebooks/minGPT-master/mingpt/model.py in __init__(self, config)
     92         self.mlp = nn.Sequential(
     93             nn.Linear(config.n_embd, 4 * config.n_embd),
---> 94             F.gelu(),
     95             nn.Linear(4 * config.n_embd, config.n_embd),
     96             nn.Dropout(config.resid_pdrop),

AttributeError: module 'torch.nn' has no attribute 'GELU'
```

**Comment by alexeib** [comment]
can you add a line "print(torch.__version__)" somewhere in your code and see what it prints

**Comment by duterscmy** [comment]
My problem is that I explort a wrong environment variable when the code runs, so exactly the wrong pytorch version was used. You can try to check it



    


            On 10/02/2020 00:49, Moon wrote: 
Hi, is there a solution now? I tried replace nn.GELU with F.gelu, but nothing changed at all. Why the message look like it's not recognizing the functional as F? I am using torch 1.6
/notebooks/minGPT-master/mingpt/model.py in __init__(self, config)
     92         self.mlp = nn.Sequential(
     93             nn.Linear(config.n_embd, 4 * config.n_embd),
---> 94             F.gelu(),
     95             nn.Linear(4 * config.n_embd, config.n_embd),
     96             nn.Dropout(config.resid_pdrop),

AttributeError: module 'torch.nn' has no attribute 'GELU'


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pytorch/fairseq/issues/2510#issuecomment-702264040",
"url": "https://github.com/pytorch/fairseq/issues/2510#issuecomment-702264040",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by cs-rukawa** [comment]
Try to define the GELU class locally.

```
from torch import Tensor
import torch.nn.functional as F

class GELU(nn.Module):
    def forward(self, input: Tensor) -> Tensor:
        return F.gelu(input)
```

then replace nn.GELU() as GELU()
