### ISSUE TITLE
Cannot reproduce the result of bart.large.cnn

### ISSUE THREAD

**Issue by JJJJane** [pytorch/fairseq#2541]
#### What is your question?
Hi, I have downloaded the bart.large.cnn model from https://github.com/pytorch/fairseq/tree/master/examples/bart, and then used the code in readme to do the inference and evaluation(https://github.com/pytorch/fairseq/tree/master/examples/bart#evaluating-the-bartlargecnn-model), but somehow I got rouge scores of 42.31, 20.21, 39.31 instead of 44.16, 21.28, 40.90 presented in readme.
Is there anything I miss when reproducing the result? Thanks!

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.7.2
 - PyTorch Version (e.g., 1.0): 1.5.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source):  pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:
 - Any other relevant information:

**Comment by neel04** [comment]
@JJJJane Due to the stochastic nature of models, there is often some difference between the expected output and actual output. You will find that if you train the model again (Probably a little longer this time) then the result would again be different. There are some steps to reproduce exact results that involve seeding and other operations. In that case, it would be advised to either experiment on your own or contact the authors of the paper themselves for guidance/help.
