### ISSUE TITLE
Optimizing GPU use when evaluating while avoiding OOM

### ISSUE THREAD

**Issue by munael** [pytorch/fairseq#2545]
#### What is your question?
How do we make the most use of available system and GPU memory while avoid CUDA OOM errors?
Currently, an `--batch-size` too high risks the generation stopping midway through an OOM.
One too low leaves the GPU memory underused and I see clear dips in GPU utilization for sub-seconds, which are probably when fairseq is fetching data for the next batch into GPU memory. This's less than ideal.

#### Code

I use `--dataset-impl mmap` and `--batch-size` of `256` or `512` (because: some long examples). Memory consumption on a V100 32GB is consistently around 30-40%, while RAM usage is around 30GB per GPU used. GPU _utilization_ is very low and hovers consistently around 20-30%.

#### What have you tried?

Raising the batch size.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.4
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `python setup.py build_ext --inplace`
 - Python version: 3.7.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: V100 's
 - Any other relevant information: N/A

**Comment by alexeib** [comment]
use --max-tokens instead of --batch-size. this will give you dynamic batches with n tokens per batch (so shorter examples will be batched together in bigger batches than longer).

you can also reverse the order of batch sorting by reversing the order in ordered_indices function in your dataset (do something like return np.lexsort(order)[::-1]), then the longest examples will go first and presumably oom right away

**Comment by narfanar** [comment]
Right. Totally forgot about `--max-tokens` in the context of generate.py.
Still seems like there's a good opportunity to manage this issue automatically, since during generation we really (usually) don't care about batches, only the overall speed.
Could we somehow catch CUDA OOM and shrink the batch accordingly, shifting the cut data onto next batches? With a flag like `--dynamic-batch-max` or `--maximize-batch`.

**Comment by kaushal0494** [comment]
I have a question similar to the context. I have Nvidia 4 V100 GPUs. I observed that during inference (either `generate.py` or `interactive.py`) only one GPU is utilized and others remain ideal.  Is there a possible way to utilize the other three GPUs as well at the inference time?  Thank you!

**Comment by narfanar** [comment]
So I have graphs of GPU util. and GPU memory util. over the course of some fairseq-generate run, and we could definitely do better in prefetching "batches" into memory even while the current batch of smaller-than-optimal size is being processed. There're very clear dips in GPU util (implying IO?):
![image](https://user-images.githubusercontent.com/5769148/92068789-23416b80-eda8-11ea-91f8-f29c52af715c.png)
And the memory graph doesn't imply any prefetching, maybe, probably:
![image](https://user-images.githubusercontent.com/5769148/92068866-4cfa9280-eda8-11ea-8392-1471a0ca1bb2.png)
