### ISSUE TITLE
How to Get the Attention Matrix ?

### ISSUE THREAD

**Issue by cocaer** [pytorch/fairseq#264]
Hi..... It seems that `interactive.py` or  `generate.py` only provides the attention maxima for each word in the hypothesis by using  `--print-alignment`. So if I want to get the attention score matrix, is there any parameter provided?

**Comment by robertodessi** [comment]
Hi, I believe you can get them from the model. For example in the fconv architecture you can get them directly from the attention layer [https://github.com/pytorch/fairseq/blob/master/fairseq/models/fconv.py#L331](url)

If you use the attention on multiple layers for this architecture the attention weights are averaged across layers so you can get the final result in avg_attention_scores here [https://github.com/pytorch/fairseq/blob/master/fairseq/models/fconv.py#L494](url)

or change the code a bit and print the matrix after every layer in the decoder.
There could be a better way but that is what I have done in the past.
For the other architecture I am not sure the best way since I mostly worked with fconv but the same idea should apply.

I am sure Myle or some other maintainers of fairseq could better help you on this.
