### ISSUE TITLE
 max-tokens and GPU memory problems

### ISSUE THREAD

**Issue by Surnal** [pytorch/fairseq#2777]
I have two GPUs with memory of 12000Mib. 
Run the translation model with fairseq, set max-tokens to 512 to run on a single GPU, and use about 10,000 memory; Set max-tokens to 256, run on two GPUs, and use about 10,000 video memories respectively.

#### Questions：

1. Why is the GPU's memory utilization rate not 10,000 in total but 10,000 respectively?
2. If it is 10000 respectively, isn't my video memory of 24000Mib equivalent to only 12000Mib? 
3. Then I won't be able to run a model with more than 12000Mib of video memory?
4. For my model problem,How can fairseq be used on two GPUs to become a total of 10,000?

The following picture shows the script of the model running on a single  GPU：
![1](https://user-images.githubusercontent.com/50646972/96844157-c1d17b00-1481-11eb-8b3f-6b610f80d37d.png)
![2](https://user-images.githubusercontent.com/50646972/96844173-c5fd9880-1481-11eb-86b0-39d930b6cec0.png)

Then a single GPU usage：
![3](https://user-images.githubusercontent.com/50646972/96844264-e2013a00-1481-11eb-9a27-82dccbf611f7.png)

The following picture shows the script of the model running on a two GPUs：
![4](https://user-images.githubusercontent.com/50646972/96844321-f2191980-1481-11eb-91d2-dd991ca81128.png)

Then two GPUs usage：
![5](https://user-images.githubusercontent.com/50646972/96844364-00ffcc00-1482-11eb-88d4-83a83a5b2a30.png)

#### What's your environment?

 - fairseq Version : Latest
 - PyTorch Version: 1.6.0
 - OS: Linux
 - How you installed fairseq: Download on github
 - Python version: 3.6.12
 - GPU models and configuration:  2 TITAN Xp
 - CUDA/cuDNN version:  cuda-10.2

@myleott 
cc: @shruti-bh

Thanks in advance!

**Comment by edunov** [comment]
Hi Surnal, 

When you train a model on multiple GPUs, fairseq works in data parallel regime, that is model parameters and optimizer states are replicated across each GPU, while the data is split. This makes effective batch size bigger, and this increases the utilization of each GPU. 
I don't quite understand why would you want to decrease utilization of GPUs, this will slow down training while keeping the overhead of data parallelism, but you can do it by decreasing the model size and decreasing the batch size (reduce --max-tokens )
If you want to keep GPUs underutilized, it would be much better to train on 1 GPU instead of 2 and keep 1 fully utilized and the other one free, since it will remove the cost of data parallelism and any communication and synchronization overheads.

**Comment by Surnal** [comment]
> Hi Surnal,
> 
> When you train a model on multiple GPUs, fairseq works in data parallel regime, that is model parameters and optimizer states are replicated across each GPU, while the data is split. This makes effective batch size bigger, and this increases the utilization of each GPU.
> I don't quite understand why would you want to decrease utilization of GPUs, this will slow down training while keeping the overhead of data parallelism, but you can do it by decreasing the model size and decreasing the batch size (reduce --max-tokens )
> If you want to keep GPUs underutilized, it would be much better to train on 1 GPU instead of 2 and keep 1 fully utilized and the other one free, since it will remove the cost of data parallelism and any communication and synchronization overheads.

Thank you very much for your answer, because my current model is too large, which leads to insufficient video memory, so I want to use 24000Mib video memory, that is, add two GPU video memories. But it can't be realized now.
