### ISSUE TITLE
Memory issue when training the transformer model

### ISSUE THREAD

**Issue by Arvid-pku** [pytorch/fairseq#2926]
#### What is your question?
Hi,
I trained the transformer model with base architecture. But out of memory happened.

#### Code
my commandline is as followed：

CUDA_VISIBLE_DEVICES=2 fairseq-train  data/data-bin/rotowire  \
    --arch transformer --share-all-embeddings --dropout 0.3 --batch-size 1 \
    --encoder-embed-dim 512 --encoder-ffn-embed-dim 2048 --encoder-layers 6 --encoder-attention-heads 8 \
    --decoder-embed-dim 512 --decoder-ffn-embed-dim 2048 --decoder-layers 6 --decoder-attention-heads 8\
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 \
    --lr 5e-6 --min-lr 1e-09 \
    --weight-decay 0.0 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --save-dir model --num-workers 2 --max-target-positions 1000 --max-source-positions 8000

#### What have you tried?
I have tried to set batch size 1/2/4/8, and num-workers 2/4/8, but they all didn't work.
ps: my input is about 5000 words, and output 800 words.

#### What's your environment?
Linux server.
GPU
Memory is 11019MiB. When I was training, it used more than 10000MiB.

**Comment by myleott** [comment]
> my input is about 5000 words

That's the problem. That's a very long input size -- self-attention is O(n**2), so you're probably running out of memory because the input is too long. Please try chunking your input into smaller subsequences, using a smaller model, or trying a more efficient architecture (e.g., the lightweight and dynamic convolution models may be more memory efficient: https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper).

**Comment by Arvid-pku** [comment]
Yeah, I tried to reduce the model's layers and heads, and it worked.
I will try other more fit models.
Thank you very much!
