### ISSUE TITLE
get near 100 BLEU score after adding --prefix-size

### ISSUE THREAD

**Issue by haorannlp** [pytorch/fairseq#2927]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I trained a Transformer and hope to generate translations using ``--sampling`` methods conditioned on gold prefixes.
#### Code
``python generate.py  data-bin/$data --path $path --batch-size 512 --sampling --beam 1 --nbest 1 --remove-bpe --prefix-size 300``
   
The max length of the sentences in my dataset is < 300. 
But I obtained a 97 BLEU score using this command. Without ``--prefix-size``, the BLEU is only around 20. 
Is this normal that my model seems to remember the previous token? Or I use a wrong command? Thank you. 

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9
 - PyTorch Version (e.g., 1.0): 1.2
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
`--prefix-size K` will use the first K tokens of the reference translation. So when you set `--prefix-size 300` it's basically copying the whole reference and you get 100 BLEU because the reference matches itself.

It's not quite clear what you're trying to achieve, but this is the expected behavior with `--prefix-size`...

**Comment by haorannlp** [comment]
@myleott Thanks. 
At test time, Transformer generates a complete sequence conditioned on its own predictions, e.g. $p(\hat{y}_t| \hat{y}_{<t},x)$ where \hat{y}_{<t} is the model's predictions so far.  But I want the model to generate a complete sequence conditioned on the gold target,  $p(\hat{y}_t| y_{<t},x)$ where y_{<t} is the gold partial sequence. This is exactly the behavior of the model at training time. So I hope the model can still generate in this way even at test time. 
That's why I want to use ``--sampling`` method since now we have a  probability distribution over the entire vocabulary $p(\hat{y}_t| y_{<t},x)$. I can sample one token from this distribution but this token is not fed as input to the next time step.

**Comment by myleott** [comment]
Hmm, we don't directly support that, since `--prefix-size` ensures that the reference tokens are selected by setting the lprobs of all other candidate words to -inf.

You might try instead using `--score-reference` (which uses SequenceScorer.py) and modifying the following code to sample instead of gather:
https://github.com/pytorch/fairseq/blob/521fccf93c821cabb3686b768f9d9152486b5bd6/fairseq/sequence_scorer.py#L54-L59

**Comment by haorannlp** [comment]
@myleott Thanks for your advice.
