### ISSUE TITLE
Datasets for Roberta pretraining

### ISSUE THREAD

**Issue by swethmandava** [pytorch/fairseq#2947]
From the paper, it seems like the model uses CC-News, Stories, Wikipedia and books corpus. 

Are there data download and processing scripts available?

For Stories, the paper cites https://arxiv.org/pdf/1806.02847.pdf and says "We evaluate all models trained on CommonCrawl after approximately 10-billion words are consumed." Does that mean Stories is C4? If yes, does it already include CC-News?

**Comment by myleott** [comment]
No, there's no connection to the C4 dataset. The STORIES dataset was a completely separate dataset released by Google here: https://github.com/tensorflow/models/tree/archive/research/lm_commonsense#1-download-data-files. Unfortunately it seems they've taken down the link 😢 

OpenWebText can be obtained here: https://skylion007.github.io/OpenWebTextCorpus/

Unfortunately, we're not able to share the other datasets (Books, Wikipedia, CC-NEWS) directly due to licensing issues.

If you're looking for large datasets for language modeling, I'd recommend checking out CC-100: http://data.statmt.org/cc-100/

**Comment by YovaKem** [comment]
Is it possible to share what the size is (in GB) of the Book Corpus and Wikipedia corpus RoBERTa is trained on?

**Comment by myleott** [comment]
The books corpus was ~4.2GB, wikipedia ~12GB.

Looks like you can get most of these datasets from here btw... https://github.com/EleutherAI/The-Pile

**Comment by jubueche** [comment]
Hi @myleott ,
Do you think you can share some steps/scripts for preprocessing the data? I understand that you can't provide the data, but I see no issue with providing the preprocessing code. I am also wondering how to combine multiple datasets for pretraining in fairseq.
Thanks :)

**Comment by PavanKumarMiriyala** [comment]
Hi @jubueche, 

Are you able to find the steps/scripts for preprocessing the data? For example, wikipedia ~12GB data in https://github.com/EleutherAI/The-Pile

@myleott can you please help on this?
