### ISSUE TITLE
Transcription timestamp of every word in the output wav2vec2

### ISSUE THREAD

**Issue by harveenchadha** [pytorch/fairseq#2965]
#### How to get the timestamp of each word in transcription in wav2vec?

Often in ASR the timestamp of each word in duration matters a lot. Is there any mechanism that does this yet?

**Comment by alexeib** [comment]
this is not really supported at the moment. you can try to add the code yourself to infer.py for viterbi decoding, or check if wav2letter decoder supports this (since our decoding is using wav2letter decoders). alternatively you can try to implement decoding with e.g. kaldi which should be straight forward since you can easily get emissions (if you do this please contribute back!) and get the timestamps from there

**Comment by irux** [comment]
@harveenchadha did you solve it ?

**Comment by harveenchadha** [comment]
@irux not yet, but will be working on it.

**Comment by pushkal1234** [comment]
How to get a word time stamp in wav2vec 2.0?
