### ISSUE TITLE
Is there any reason to report log score in base 2 instead of base e?

### ISSUE THREAD

**Issue by haorannlp** [pytorch/fairseq#3009]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
When we run generate.py, the hypotheses avg. log likelihood and the positional log likelihood are all in base 2. Is there a reason to report log2(.)  instead of ln(.) ?
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9
 - PyTorch Version (e.g., 1.0): 1.2
 - OS (e.g., Linux): linux
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
It's just historical convention, since a lot of these things were originally defined in terms of "bits" (base 2), whereas the frameworks implement them in terms of "nats" (base e). The "Bits-per-character and bits-per-word" section of this blog briefly discusses this: https://thegradient.pub/understanding-evaluation-metrics-for-language-models/
