### ISSUE TITLE
Translations using Transformer

### ISSUE THREAD

**Issue by sarthmit** [pytorch/fairseq#3180]
I am trying to train new transformer models for various different translation tasks (de-en, fr-en, ru-en, etc.) and their reverse. While I see ways of doing de-en using transformer, where should I look to

1. Preprocess the other translation datasets - eg. ru-en, etc.
2. Train transformer models for these various translation pairs

**Comment by lematt1991** [comment]
The only thing that should really differ in preprocessing of different languages is tokenization.  If you use something like [moses](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/tokenizer.perl), you can specify the language in the commane (`-l ru` instead of `-l de`).  As far as hyperparameters for training the model, this will depend on your training data.  Start with what you use for training the german model, and experiment from there.

**Comment by sarthmit** [comment]
The model side is clear to me. On the data side, I am using the following script for english to german (for example):
[https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-wmt14en2de.sh](https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-wmt14en2de.sh)
Is there a similar script available that lets me specify the language pair and downloads and tokenizes that pair?

**Comment by lematt1991** [comment]
You'll need to write your own script to fetch the en/ru data, but you should be able to re-use most of the script you linked to.  You'll just need to change the [languages](https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-wmt14en2de.sh#L54-L56) and find the sources for the parallel English Russian data.

**Comment by sarthmit** [comment]
So I will have to change the URLs, FILEs, and CORPORAs along with the language pairings, and that should be it?

**Comment by lematt1991** [comment]
Yep, that should be it.  Feel free to follow up here if you run into problems.  I'm going to close the task for now.
