### ISSUE TITLE
Cannot reproduce the CoVoST ST model scores

### ISSUE THREAD

**Issue by patil-suraj** [pytorch/fairseq#3310]
#### What is your question?

I'm trying to evaluate the CoVoST2 checkpoints given [here](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/covost_example.md) but the scores are very different from the reported scores.

I'm getting the following BLEU scores

- en_de: 1.87
- fr_en:  3.86
- es_en: 3.03

While the reported scores are

- en_de: 16.3
- fr_en:  26.3
- es_en: 23.0

#### Code

I'm using the same pre-processing and evaluation commands given in the [README](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/covost_example.md)

Here's a [colab](https://colab.research.google.com/drive/1vrK8lI0K3Jsgc6Hfbn9IDfvccMS0lBUS?usp=sharing) to reproduce the issue using the `covost2_es_en_st_transformer_s.pt` checkpoint for `en-es` ST.

   

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 17.1
 - OS (e.g., Linux):Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): 
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: TITAN RTX

cc @kahne

**Comment by kahne** [comment]
Thanks for reporting the issue! This seems to be caused by a discrepancy on VBR MP3 (Common Voice's audio format) decoding. The checkpoints were using GStreamer while the new script here uses SoX. The former seems to have slightly longer padding (2 more fbank features as a result). We will update the checkpoints to fix this inconsistency. I will let you know when they are available.
