### ISSUE TITLE
Clarifications on src-file format in Evaluation of SimulST on MuST-C

### ISSUE THREAD

**Issue by Onoratofra** [pytorch/fairseq#3356]
I am following the Readme file on SimulST. I am having troubles with the evaluation phase as it is not clear to me which format should be used for : `--src-file ${SRC_LIST_OF_AUDIO}`

I have tried to set it to the root folder containing the audio files or even writing the entire list of absolute audio paths in a txt file, but none of the two options worked.

Could you share an example of what you mean by SRC_LIST_OF_AUDIO, please?
Thank you very much in advance

**Comment by mzaidi59** [comment]
The recent [update](https://github.com/pytorch/fairseq/commit/dd74992d0d143155998e9ed4076826bcea80fb06) provides clarity on this, you can refer to the [guide](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md).

The source file ${SRC_LIST_OF_AUDIO} is a list of paths of audio files. Assuming your audio files stored at /home/user/data, it should look like this
```
/home/user/data/audio-1.wav
/home/user/data/audio-2.wav
```
Each line of target file ${TGT_FILE} is the translation for each audio file input.
```
Translation_1
Translation_2
```

**Comment by Onoratofra** [comment]
I have tried to follow the new instructions but I still have one question: do you consider as input file an entire Ted talk or only a fragment of it that corresponds to uttering one sentence? In case you used the latter, can you upload the code you used to divide each wav file into the utterances of the single sentences?

In case you considered the entire talk, as I did, how did you manage to get approx 12 Bleu? I get approx 0 but I have used your saved checkpoint and databin folder.

Thank you very much in advance for your help! 
cc @xutaima

**Comment by xutaima** [comment]
Thank you so mush @mzaidi59 for your answer.

Hi @Onoratofra, sorry for the late reply on the previous issue. We evaluate the model on segmented audio rather than the entire talk. The segmentation is from a yaml file which comes along with the Must C dataset. At the moment, the [data preparation](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/simulst_mustc_example.md#data-preparation) only stores the features but not the actual audio files for the segmented audio. We plan to update a script to generate the segmentations and this `${SRC_LIST_OF_AUDIO}` file very soon.
