### ISSUE TITLE
Can I change the the model so I'll get more than 12 results in nbest

### ISSUE THREAD

**Issue by ShiraKadosh** [pytorch/fairseq#342]
1. How can I control the number of n-best options the model output when I use it on the test set?
currently there are 12 I would like to get the top 100.
2. What is the 'S' and 'A' in the n-best output file, I understand that 'O' is the output and the 'H' are the hypothesis.
3. The hypotheses are ordered descending by the negative score:
H	-0.15562120079994202	The results clearly show that our method significantly exceed the current state of the art
What is that score?
Thanks!

**Comment by myleott** [comment]
You can use the --nbest flag to output more. Note that you also need --beam to be greater than or equal to --nbest otherwise it will not generate enough hypotheses.

S is the source, A is the attention alignment over the source. In H, the score is the average per-token log probability of the sentence.

**Comment by ShiraKadosh** [comment]
Thanks @myleott
