### ISSUE TITLE
Error: "ConfigKeyError: str interpolation key 'model.mask_length' not found" when loading pretrained vq-wav2vec model

### ISSUE THREAD

**Issue by shuangwei123** [pytorch/fairseq#3512]
#### What is your question?

I encountered Error: "ConfigKeyError: str interpolation key 'model.mask_length' not found" when trying to load pretrained vq-wav2vec-kmean model.

#### Code

import torch
import fairseq

#cp = torch.load('/content/gdrive/MyDrive/vq-wav2vec_kmeans.pt')
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['/content/gdrive/MyDrive/vq-wav2vec_kmeans.pt'], 
                                        )
model = model[0]
model.eval()

#### Error log

---------------------------------------------------------------------------
ConfigKeyError                            Traceback (most recent call last)
<ipython-input-8-db58c0cd7727> in <module>()
      3 
      4 cp = torch.load('/content/gdrive/MyDrive/vq-wav2vec_kmeans.pt')
----> 5 model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(['/content/gdrive/MyDrive/vq-wav2vec_kmeans.pt'], 
      6                                         )
      7 model = model[0]

8 frames
/usr/local/lib/python3.7/dist-packages/omegaconf/base.py in _resolve_simple_interpolation(self, key, inter_type, inter_key, throw_on_missing, throw_on_resolution_failure)
    326                 if throw_on_resolution_failure:
    327                     raise ConfigKeyError(
--> 328                         f"{inter_type} interpolation key '{inter_key}' not found"
    329                     )
    330                 else:

ConfigKeyError: str interpolation key 'model.mask_length' not found

**Comment by leo19941227** [comment]
Just for a reference, I find that the error is caused by the following commit which enables TPU training via preparing masks in the dataloader, but as a consequence adds additional arguments to the `audio_pretraining` task and assuming the model config will give the actual values of those arguments. So you can see there is a "mask_length" argument in the `wav2vec2.py`. However, this is not the case for `wav2vec.py` which is used for both wav2vec and vq-wav2vec.
