### ISSUE TITLE
The questions about EOS in the sentences

### ISSUE THREAD

**Issue by travel-go** [pytorch/fairseq#376]
Hello:
I observed a phenomenon that the source-side sentence is padded to the left, and EOS is at the end of the sentence, the target-side sentence is filled to the right, and EOS is at the beginning of the sentence.
I am curious about what happens if the EOS of the source sentence is placed at the beginning of the sentence and then padded on the right. The target sentence is still filled on the right and EOS is placed at the beginning of the sentence. What will it do?

I am looking forward to your reply.

**Comment by myleott** [comment]
I doubt it would make much difference. The main reason we do left-padding on the source is for historical reasons to match the Lua version of fairseq.

You can test this yourself by passing `--left-pad-source "False"`. See the argument definition here: https://github.com/pytorch/fairseq/blob/693894b6de4af34af10789906e7ece5be2e78989/fairseq/tasks/translation.py#L53-L54

Re: EOS, we reuse the EOS symbol in the decoder to indicate the beginning-of-sentence. We've experimented in the past with a distinct beginning-of-sentence symbol but we didn't observe a difference.

**Comment by travel-go** [comment]
@myleott 
Thank you for your reply. Maybe what I said is not very clear. For example：
The original source sentence: <pad>,<pad>,<pad>,1,2,3,4,<eos>
The sentence I want to be:<eos>,1,2,3,4,<pad>,<pad>,<pad>
The target sentences remain unchanged.
I would like to know whether such changes will affect the training effect.
I've already tried this.

**Comment by KelleyYin** [comment]
https://github.com/pytorch/fairseq/blob/a442244db661a30fe70ee46a96593c94659414f7/fairseq/data/language_pair_dataset.py#L44-L52

You should refer to above code. This code is used to pad a batch of target sentences. 
The flag `left_pad` means padding in the left of sentence, so you could set this to `False` depending on what you want.
The another flag is `move_eos_to_beginning`, which means the symbol of EOS is added to the beginning of sentence . Therefore, you should set it to`True.`

**Comment by travel-go** [comment]
I also know this code. Nevertheless, did you see the eos is used  in the source sentences? or did you know this change will affect the training effect.

**Comment by maxdel** [comment]
@KelleyYin @travel-go There is no consensus on using EOS/BOS in the source. See e.g. this for more info: https://github.com/allenai/allennlp/issues/611

However, it seems like in fairseq, during teacher forcing the EOS is **_moved_** to the beginning of the sentence. This way this EOS token can be fed as an input at the first decoder timestep during inference.

 @myleott, so you remove it from the end of the target during training. Do you still teach a model to generate EOS at the end of the sentence (so that you know where to trim the hypothesis)?

**Comment by myleott** [comment]
@travel-go, interesting, thanks for clarifying. I doubt this would have much of an effect, but it may be problem/dataset dependent. For example, the pytorch/translate code doesn't use any source-side EOS, since they found it wasn't helpful for translation.

@maxdel, yes, we move the EOS to the beginning for teacher forcing (prev_output_tokens), but the targets remain unchanged (i.e., EOS is at the end). At the first time step the decoder takes in an EOS (which acts as a beginning-of-sentence marker) and the target is the first output word, ..., then at the last time step it takes in the final output word (the last position of prev_output_tokens) and the target is EOS. For example, we might have:
```
prev_output_tokens: [eos, a, b, c]
            target: [a, b, c, eos]
```
