### ISSUE TITLE
Cannot reproduce the result of speech translation task on Covost-v2 dataset(en_zh-CN and zh-CN_en)

### ISSUE THREAD

**Issue by Shengqiang-Li** [pytorch/fairseq#3814]
#### What is your question?

cannot reproduce the result of speech translation task on Covost-v2 dataset, (egs, en_zh-CN and zh-CN_en).
I got the following bleu scores:
en_zh-CN: 4.61
zh-CN_en: 5.61
while the reported score are:
en_zh-CN: 25.4
zh-CN_en: 5.8

#### Code

I'm using the same pre-processing and evaluation commands given in the README

#### What's your environment?

 - fairseq Version (1.0r):
 - PyTorch Version (1.9)
 - OS (Linux):
 - How you installed fairseq (source):
 - Build command you used (pip install --editable ./):
 - Python version: 3.8
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: 2080ti
 - Any other relevant information:

**Comment by kahne** [comment]
Hi @Shengqiang-Li , we evaluated En-Zh using character-level BLEU (add `--sacrebleu-char-level` to `fairseq-generate`) for simplicity. Without additional word segmentation, word-level BLEU won't work normally on Chinese and hence it results in low BLEU. The difference on Zh-En seems acceptable given the randomness during model training.

**Comment by florallam** [comment]
Hello there!! I'm currently trying to train a fairseq ASR using the covost dataset (Indonesian). I've been trying to find individuals who have successfully trained their ASR from scratch (seems like yours is successful since Chinese ASR has to be done from scratch prior to speech translation), as I've been having trouble with obtaining an ASR with WER or >100. Were there additional hyperparameters that you did or steps in addition to the steps that were mentioned [here](https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_text/docs/covost_example.md)?
