### ISSUE TITLE
Simultaneous translation model (MMA) can't generate

### ISSUE THREAD

**Issue by kurtisxx** [pytorch/fairseq#3876]
## 🐛 Bug

I've trained the command provided in the README to train a simultaneous machine translation model (MMA-Hard) model. The command I used is the following:

`CUDA_VISIBLE_DEVICES=0 python train.py ./data-bin/wmt15_de_en --simul-type hard_aligned     --mass-preservation     --criterion latency_augmented_label_smoothed_cross_entropy      --latency-weight-var  0.1     --max-update 50000     --arch transformer_monotonic_iwslt_de_en     --optimizer adam --adam-betas '(0.9, 0.98)'     --lr-scheduler 'inverse_sqrt'     --warmup-init-lr 1e-7  --warmup-updates 4000     --lr 5e-4 --stop-min-lr 1e-9 --clip-norm 0.0 --weight-decay 0.0001    --dropout 0.3     --label-smoothing 0.1    --max-tokens 3584
`
After traning completed, I wanted to  generate translations using use the last checkpoint saved during training. For this I run following command:

`fairseq-generate ./data-bin/wmt15_de_en/ --path checkpoints/checkpoint_last.pt --simul-type hard_aligned --max-tokens 3584
`
I ended up with the following error message:
```

  File "anaconda3/envs/pytorch_latest_p36/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "fairseq/fairseq_cli/generate.py", line 404, in cli_main
    main(args)
  File "fairseq/fairseq_cli/generate.py", line 49, in main
    return _main(cfg, sys.stdout)
  File "fairseq/fairseq_cli/generate.py", line 206, in _main
    constraints=constraints,
  File "fairseq/fairseq/tasks/fairseq_task.py", line 501, in inference_step
    models, sample, prefix_tokens=prefix_tokens, constraints=constraints
  File "anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "fairseq/fairseq/sequence_generator.py", line 182, in generate
    return self._generate(sample, **kwargs)
  File "fairseq/fairseq/sequence_generator.py", line 325, in _generate
    self.temperature,
  File "fairseq/fairseq/sequence_generator.py", line 778, in forward_decoder
    incremental_state=incremental_states[i],
  File "fairseq/fairseq/models/transformer.py", line 806, in forward
    alignment_heads=alignment_heads,
  File "fairseq/examples/simultaneous_translation/models/transformer_monotonic_attention.py", line 214, in extract_features
    .gather(1, curr_steps.t())
RuntimeError: Index tensor must have the same number of dimensions as input tensor
```

What could be the reason for that? I'm really DISAPPOINTED that there are millions of problems in the official code of a published paper and no support at all.. @xutaima 

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

 - fairseq Version (e.g., 1.0 or master): 252d5a9ae93e68254cfb1896fb5624cf11cda15e ( commit id)
 - PyTorch Version (e.g., 1.0) 1.7
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): git checkout 252d5a9ae93e68254cfb1896fb5624cf11cda15e && pip install —editable ./
 - Python version: 3.6.13
 - CUDA/cuDNN version:10.1
 - GPU models and configuration: v100
 - Any other relevant information:

**Comment by George0828Zhang** [comment]
I also have this issue.  AFAIK `fairseq-generate` is not meant to support simultaneous translation. The default SequenceGenerator uses full encoder context, and runs beam search on the decoder. Much like non-autoregressive translation, this task needs a new SequenceGenerator class!
If you want evaluation you should run SimulEval as instructed by the documentation.
Meanwhile, I do hope simultaneous translation gets a new SequenceGenerator class in order to make both `fairseq-generate` and `--eval-bleu` work.

**Comment by xutaima** [comment]
Hi @kurtisxx, thanks for your feedback. As @George0828Zhang mentioned you need to use [SimulEval](https://github.com/facebookresearch/SimulEval) instead of sequence generator to decoder since the sequence generator assumes static encoder states. Even implementing a new sequence generator can be non-trivial and tricky for latency evaluation. Sorry we haven't updated the document for WMT EnDe decoding, but you could take a look at[ IWSLT EnJa](https://github.com/pytorch/fairseq/blob/master/examples/simultaneous_translation/docs/enja-waitk.md) as an example. We are working on bug fixing and document updating.

**Comment by kurtisxx** [comment]
Hi @xutaima, @George0828Zhang  Thanks for the pointers and explanation. I'll have a look at EnJa example, for sure. Hope to see fixes to other problems related to this model soon :) Best.

**Comment by EricLina** [comment]
> Hi @xutaima, @George0828Zhang Thanks for the pointers and explanation. I'll have a look at EnJa example, for sure. Hope to see fixes to other problems related to this model soon :) Best.

Hello , have you finished Ende Evaluation  ?  Could you please share your Agent.py ， thank you
