### ISSUE TITLE
Is it possible to do incremental learning ?

### ISSUE THREAD

**Issue by ShiraKadosh** [pytorch/fairseq#405]
Hi,
I would like to keep training a model that finish training on old data with new data,
the issue is that the vocabularies of src and trg languages will change.
Is it possible to do that?
And if yes, how should  I add the new data? should I run preprocess.py again on the new data and then the train.py?

Thanks

**Comment by huihuifan** [comment]
It's not possible to pick up training if your vocabulary has changed without making some code modifications- this is because the input/output embedding layers won't have trained your new vocabulary. I would suggest: use BPE and maintain the same BPE codes for your old/new data, then train with a set vocabulary that's equal to the # of BPE tokens you have. Then there is no mismatch. You need to preprocess both datasets of course.

Hope that helps!
