### ISSUE TITLE
 select multi words in one beam?

### ISSUE THREAD

**Issue by mali-nuist** [pytorch/fairseq#555]
The fariseq may select multi words in one beam as the program view the lprobs of shape [batch, beam_size, vocab_size] to [batch, beam_size * vocab_size] and then select the largest cand_size logprobs from each row.  Does this effect the final result ?  
https://github.com/pytorch/fairseq/blob/5869385c4badbacdca6d6fd110f9f2af137cebf4/fairseq/search.py#L73-L82
##### ---------------------------------------------------
Besides, what will happen if more than beam size EOSs occur in one decoding step? it seems that the index of EOS flag in active_hypos[active_mask]  may >= the cand_size which may cause the indexOutofBound error when executing the torch.gather.  
https://github.com/pytorch/fairseq/blob/5869385c4badbacdca6d6fd110f9f2af137cebf4/fairseq/sequence_generator.py#L470-L473

**Comment by myleott** [comment]
> The fariseq may select multi words in one beam

Yes, this is intentional. Beam search can prune some beams and select multiple hypotheses from other beams, as long as the total number of selected hypotheses is K at each step.

> what will happen if more than beam size EOSs occur in one decoding step

This shouldn't happen, since we choose 2*K candidates from K beams. Each beam can produce at most one eos hypothesis, so there are at most K eos hypotheses.

**Comment by mali-nuist** [comment]
@myleott  Thanks for your interpretation , i forgot the 2k candidates comes from k beam~~~
