### ISSUE TITLE
ImportError: cannot import name 'Tokenizer'

### ISSUE THREAD

**Issue by 2hip3ng** [pytorch/fairseq#581]
When I learning 'Tutorial: Classifying Names with a Character-Level RNN' of the full documentation, I found that error. In registering a new task of 'Tutorial: Classifying Names with a Character-Level RNN', how should I to overcome it?
![image](https://user-images.githubusercontent.com/38064349/54472264-86c88980-4800-11e9-95a1-961bb8a37365.png)

**Comment by 2hip3ng** [comment]
多谢，刚刚找了一个tokenizer.py替换掉了，然后可以啦

**Comment by huihuifan** [comment]
Thanks for finding that- if you want to make a fix, could you make a pull request? Thank you!

**Comment by 2hip3ng** [comment]
I have made a pull request to recover the tokenizer.py .

**Comment by huihuifan** [comment]
Thank you, I am closing this issue.

**Comment by davidecaroselli** [comment]
Hello!

I am facing the same issue here and I am not able to use the new fairseq v0.6.2 that I suppose now that is a faulty release (maybe?).
I'm not sure why this issue has been closed even if the solution has not been merged yet into the master branch.

My question is: was the Tokenizer class removal intentional or not? If yes, what is the new official way to tokenize (aka 'transform from string to IntTensor')?

Thanks!

**Comment by davidecaroselli** [comment]
Maybe this? https://github.com/pytorch/fairseq/blob/master/fairseq/data/dictionary.py#L220

But if this is the new intended way to do it, why a pull request to restore the Tokenizer that, to my understanding, has been deprecated?

**Comment by mali-nuist** [comment]
i do not think that it is deprecated, because some other places still using the tonknzie.Tokenizer . You can search in the src code!

**Comment by myleott** [comment]
Yes, tokenizer was meant to be deprecated, but we forgot to update the tutorial. The new way of tokenizing is with Dictionary.encode_line, which will be more general as we eventually support swapping in alternate Dictionary implementations.
