### ISSUE TITLE
[Feature Proposal] Add image captioning example

### ISSUE THREAD

**Issue by zhiqwang** [pytorch/fairseq#759]
Hi fairseq team!

As mentioned in issue #90,  #313 and #475 , there are plenty of places where vision and language intersect (e.g., image captioning, VQA). And I have written an image captioning example based on this excellent `fairseq` toolkit, I want to know whether there is a plan to add an image captioning / text recognition example?

My implementation is in my `text-recognition` [branch](https://github.com/zhiqwang/fairseq/tree/text-recognition), current structure is only [CRNN](https://arxiv.org/abs/1507.05717) with a `CTCLoss` criterion.

My next plan is add attention module and transformer module to image captioning task based on fairseq's official implementation modules.

**Comment by lematt1991** [comment]
I'm not aware of any plans to add an image captioning or text recognition example.  Feel free to submit a PR!

**Comment by krasserm** [comment]
Together with @cstub, I started to work on an [image captioning extension](https://github.com/krasserm/fairseq-image-captioning) for fairseq. Still early-access but you can already train transformer-based image captioning models. There's also a simple demo and a pre-trained model available. More details in the project's README.

**Comment by adrelino** [comment]
I am also interested in combining vision and and language.

Both of you re-implemented a CNN-based encoder to get an intermediate feature representation from images: [image_captioning_encoder](https://github.com/zhiqwang/fairseq/blob/text-recognition/fairseq/models/image_captioning_encoder.py#L109) @zhiqwang  or [inception_v3](https://github.com/krasserm/fairseq-image-captioning/blob/wip-train-inception/model/inception.py) @krasserm. This is then fed into fairseq's LSTM/Transformer -based decoder to generate the captions.

Instead of re-implementing the feature extractor, I am wondering if anyone ever tried to combine fairseq with a Faster-RCNN object-based feature extractor from [torchvision](https://pytorch.org/docs/stable/torchvision/models.html#faster-r-cnn) or [detectron2](
https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml)?

**Comment by zhiqwang** [comment]
Hi @adrelino , I am also interested in connecting `fairseq` and `detectron2` together, maybe we can cooperate in doing this?

**Comment by krasserm** [comment]
@adrelino in [fairseq-image-captioning](https://github.com/peteanderson80/bottom-up-attention) you can already use [pre-computed features extracted with a Faster-RCNN](https://github.com/peteanderson80/bottom-up-attention) for training transformer-based captioning models by using the command line option `--features obj`. These are pre-computed for the MS-COCO dataset and split into Karpathy train, validation and test sets.

At the moment, I only use these pre-computed features. A later version of fairseq-image-captioning will then use a Faster-RCNN directly and implementations from torchvision or detectron2 are good candidates. This will also allow fine-tuning the object detector together with the image captioning model (which will probably require a larger dataset than MS-COCO). Happy to collaborate on that or accept pull requests. 

At the moment, I'm implementing [Self-critical Sequence Training for Image Captioning](https://arxiv.org/abs/1612.00563) and have already promising results. It took me a while to implement as I had to re-write the sequence generator so that it can also be used during training i.e. supports back-propagation (which is not supported by the default sequence generator in fairseq). Should be on Github soon. 

Afterwards, I initially planned to implement [M2: Meshed-Memory Transformer for Image Captioning](https://arxiv.org/abs/1912.08226) which requires some extensions to the transformer implementation in fairseq but I'm also open to give a Faster-RCNN implementation a higher priority if you are interested in a collaboration.

Regarding

>  This is then fed into fairseq's LSTM/Transformer -based decoder to generate the captions.

fairseq-image-captioning also supports feeding extracted features into a transformer encoder for self-attention on visual "tokens" and then feeding the encoder output into a transformer decoder. Using a transformer encoder can be enabled with the `--arch default-captioning-arch` command line option.

**Comment by logicwong** [comment]
Recently we propose a unified multimodal pretrained model named OFA ( https://github.com/OFA-Sys/OFA, the code is based on fairseq), which achieves new state-of-the-art performance in COCO image captioning (~149.6 cider) without any off-the-shelf detector. In addition, OFA also achieves state-of-the-art performance in a series of vision&language tasks (such as text-to-image generation, VQA, visual grounding, etc.). More implementation details are provided in the README. We plan to release more interesting tasks and applications in the near future.
