### ISSUE TITLE
--score-reference while generating translations

### ISSUE THREAD

**Issue by aastha19** [pytorch/fairseq#833]
Hi

I would want to ask the purpose of --score-reference and whether it should be used while generating the BLEU score as it makes a huge difference in the score.

**Comment by pipibjc** [comment]
No, it should not be used when we want to evaluate BLEU scores. `--score-reference` option is used to evaluate how your machine translation model score each token of the given target sentences (log-loss, not BLEU score). With the option, the output hypothesis sentences will be exactly the same as reference sentences because we only do scoring instead of generation, therefore we will always get 100 BLEU score.
